Log every non root new process started/failed on the endpoint
SUSE/linux-security-sensor pull request #23
Opened 2022-04-13 19:21 UTC by chajain

Log every new process started/failed on the endpoint

2022-04-13 19:53 UTC, guangyee approved these changes
Looks good! Thanks Charu!

2022-04-14 00:48 UTC, Firstyear requested changes

2022-04-14 00:48 UTC, Firstyear commented on artifacts/definitions/Linux/Events/ProcessStatuses.yaml
> +              regex_replace(source=read_file(filename= "/proc/" + PPID + "/cmdline"),
What happens if the process is dead before we got to read this from proc?

2022-04-22 00:05 UTC, Firstyear approved these changes

2022-04-22 22:54 UTC, guangyee commented on artifacts/definitions/Linux/Events/ProcessStatuses.yaml
> +     LET _ <= SELECT * FROM execve(argv=["/bin/bash", "-c", "if [ ! -f /etc/audit/rules.d/vrr_proexec.rules ]; then echo -e '-a always,exit -F arch=b64 -S execve -F euid!=0 -F auid!=-1 -k vrr_proexec
`>` instead of `>>` as you are only writing the file once

2022-05-20 00:32 UTC, chajain commented
https://github.com/SUSE/linux-security-sensor/pull/34

2022-05-20 00:32 UTC, closed without merging