SUSE.Linux.Events.Crontab: Add task execution artifacts
SUSE/linux-security-sensor pull request #76
Opened 2023-10-19 18:33 UTC by xTeixeira

Parse cron task executions from syslog and journal.

2023-11-14 17:09 UTC, djoreilly requested changes

2023-11-14 17:09 UTC, djoreilly commented on artifacts/definitions/SUSE/Linux/Events/Cron.yaml
> +        WHERE _TRANSPORT != 'kernel' AND _SYSTEMD_UNIT = CronSystemdUnit and Event.action = "CMD"
This is not working for me on Tumbleweed - I have the patch for https://github.com/SUSE/linux-security-sensor/pull/75 installed.  
```
 # crontab -l
*/1 * * * * /usr/bin/date
```
 Looking at the JSON from `watch_journal()` it seems `_SYSTEMD_UNIT` is `session-c387.scope` and not `cron.service`.

2023-11-16 15:06 UTC, xTeixeira commented on artifacts/definitions/SUSE/Linux/Events/Cron.yaml
> +        WHERE _TRANSPORT != 'kernel' AND _SYSTEMD_UNIT = CronSystemdUnit and Event.action = "CMD"
It looks like Tumbleweed uses a custom PAM config for cronie which causes it to create a new session scope for executing cron tasks, meaning the logs become unassociated with the original systemd unit.

I'll see if I can modify this to not rely on `_SYSTEMD_UNIT` to query events, as it won't always be the same. Relying on `_COMM = "cron"` might be enough.

2023-11-16 15:48 UTC, xTeixeira commented on artifacts/definitions/SUSE/Linux/Events/Cron.yaml
> +        WHERE _TRANSPORT != 'kernel' AND _SYSTEMD_UNIT = CronSystemdUnit and Event.action = "CMD"
Opened PR #80 against 0.7.0 with this problem fixed.

2023-11-16 15:52 UTC, xTeixeira commented on artifacts/definitions/SUSE/Linux/Events/Cron.yaml
> +        WHERE _TRANSPORT != 'kernel' AND _SYSTEMD_UNIT = CronSystemdUnit and Event.action = "CMD"
@djoreilly Do we still want this merged on 0.6.7 or are we only going to work on 0.7.0 going forward?

2023-11-16 16:05 UTC, djoreilly commented on artifacts/definitions/SUSE/Linux/Events/Cron.yaml
> +        WHERE _TRANSPORT != 'kernel' AND _SYSTEMD_UNIT = CronSystemdUnit and Event.action = "CMD"
I think we are only going to work on 0.7.0 from now on

2024-01-19 12:16 UTC, closed without merging

2024-01-19 12:16 UTC, djoreilly commented
moved to https://github.com/SUSE/linux-security-sensor/pull/80